#CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          submodules: recursive

      - name: Install Build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          bash bc binutils build-essential bzip2 cpio diffutils \
          file findutils g++ gcc gzip m4 make patch perl rsync \
          sed tar unzip wget gawk

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-images-${{ steps.vars.output.sha_short }}
          path: buildroot/output/images/
